module Chemical.Atom (atomList) where

import GHC.TypeLits

data Props = Props
  { name :: String,
    symbol :: String,
    charge :: Nat,
    color :: (Nat, Nat, Nat),
    radius :: Float
  }
  deriving (Show)

atomList :: [Props]
atomList =
  [ Props {name = "hydrogen", symbol = "H", charge = 1, color = (0, 0, 0), radius = 53.0},
    Props {name = "helium", symbol = "He", charge = 2, color = (0, 0, 0), radius = 31.0},
    Props {name = "lithium", symbol = "Li", charge = 3, color = (0, 0, 0), radius = 167.0},
    Props {name = "beryllium", symbol = "Be", charge = 4, color = (0, 0, 0), radius = 112.0},
    Props {name = "boron", symbol = "B", charge = 5, color = (0, 0, 0), radius = 87.0},
    Props {name = "carbon", symbol = "C", charge = 6, color = (0, 0, 0), radius = 67.0},
    Props {name = "nitrogen", symbol = "N", charge = 7, color = (0, 0, 0), radius = 56.0},
    Props {name = "oxygen", symbol = "O", charge = 8, color = (0, 0, 0), radius = 48.0},
    Props {name = "fluorine", symbol = "F", charge = 9, color = (0, 0, 0), radius = 42.0},
    Props {name = "neon", symbol = "Ne", charge = 10, color = (0, 0, 0), radius = 38.0},
    Props {name = "sodium", symbol = "Na", charge = 11, color = (0, 0, 0), radius = 190.0},
    Props {name = "magnesium", symbol = "Mg", charge = 12, color = (0, 0, 0), radius = 145.0},
    Props {name = "aluminium", symbol = "Al", charge = 13, color = (0, 0, 0), radius = 118.0},
    Props {name = "silicon", symbol = "Si", charge = 14, color = (0, 0, 0), radius = 111.0},
    Props {name = "phosphorus", symbol = "P", charge = 15, color = (0, 0, 0), radius = 98.0},
    Props {name = "sulfur", symbol = "S", charge = 16, color = (0, 0, 0), radius = 88.0},
    Props {name = "chlorine", symbol = "Cl", charge = 17, color = (0, 0, 0), radius = 79.0},
    Props {name = "argon", symbol = "Ar", charge = 18, color = (0, 0, 0), radius = 71.0},
    Props {name = "potassium", symbol = "K", charge = 19, color = (0, 0, 0), radius = 243.0},
    Props {name = "calcium", symbol = "Ca", charge = 20, color = (0, 0, 0), radius = 194.0},
    Props {name = "scandium", symbol = "Sc", charge = 21, color = (0, 0, 0), radius = 184.0},
    Props {name = "titanium", symbol = "Ti", charge = 22, color = (0, 0, 0), radius = 176.0},
    Props {name = "vanadium", symbol = "V", charge = 23, color = (0, 0, 0), radius = 171.0},
    Props {name = "chromium", symbol = "Cr", charge = 24, color = (0, 0, 0), radius = 166.0},
    Props {name = "manganese", symbol = "Mn", charge = 25, color = (0, 0, 0), radius = 161.0},
    Props {name = "iron", symbol = "Fe", charge = 26, color = (0, 0, 0), radius = 156.0},
    Props {name = "cobalt", symbol = "Co", charge = 27, color = (0, 0, 0), radius = 152.0},
    Props {name = "nickel", symbol = "Ni", charge = 28, color = (0, 0, 0), radius = 149.0},
    Props {name = "copper", symbol = "Cu", charge = 29, color = (0, 0, 0), radius = 145.0},
    Props {name = "zinc", symbol = "Zn", charge = 30, color = (0, 0, 0), radius = 142.0},
    Props {name = "gallium", symbol = "Ga", charge = 31, color = (0, 0, 0), radius = 136.0},
    Props {name = "germanium", symbol = "Ge", charge = 32, color = (0, 0, 0), radius = 125.0},
    Props {name = "arsenic", symbol = "As", charge = 33, color = (0, 0, 0), radius = 114.0},
    Props {name = "selenium", symbol = "Se", charge = 34, color = (0, 0, 0), radius = 103.0},
    Props {name = "bromine", symbol = "Br", charge = 35, color = (0, 0, 0), radius = 94.0},
    Props {name = "krypton", symbol = "Kr", charge = 36, color = (0, 0, 0), radius = 88.0},
    Props {name = "rubidium", symbol = "Rb", charge = 37, color = (0, 0, 0), radius = 265.0},
    Props {name = "strontium", symbol = "Sr", charge = 38, color = (0, 0, 0), radius = 219.0},
    Props {name = "yttrium", symbol = "Y", charge = 39, color = (0, 0, 0), radius = 212.0},
    Props {name = "zirconium", symbol = "Zr", charge = 40, color = (0, 0, 0), radius = 206.0},
    Props {name = "niobium", symbol = "Nb", charge = 41, color = (0, 0, 0), radius = 198.0},
    Props {name = "molybdenum", symbol = "Mo", charge = 42, color = (0, 0, 0), radius = 190.0},
    Props {name = "technetium", symbol = "Tc", charge = 43, color = (0, 0, 0), radius = 183.0},
    Props {name = "ruthenium", symbol = "Ru", charge = 44, color = (0, 0, 0), radius = 178.0},
    Props {name = "rhodium", symbol = "Rh", charge = 45, color = (0, 0, 0), radius = 173.0},
    Props {name = "palladium", symbol = "Pd", charge = 46, color = (0, 0, 0), radius = 169.0},
    Props {name = "silver", symbol = "Ag", charge = 47, color = (0, 0, 0), radius = 165.0},
    Props {name = "cadmium", symbol = "Cd", charge = 48, color = (0, 0, 0), radius = 161.0},
    Props {name = "indium", symbol = "In", charge = 49, color = (0, 0, 0), radius = 156.0},
    Props {name = "tin", symbol = "Sn", charge = 50, color = (0, 0, 0), radius = 145.0},
    Props {name = "antimony", symbol = "Sb", charge = 51, color = (0, 0, 0), radius = 133.0},
    Props {name = "tellurium", symbol = "Te", charge = 52, color = (0, 0, 0), radius = 123.0},
    Props {name = "iodine", symbol = "I", charge = 53, color = (0, 0, 0), radius = 115.0},
    Props {name = "xenon", symbol = "Xe", charge = 54, color = (0, 0, 0), radius = 108.0},
    Props {name = "caesium", symbol = "Cs", charge = 55, color = (0, 0, 0), radius = 298.0},
    Props {name = "barium", symbol = "Ba", charge = 56, color = (0, 0, 0), radius = 253.0},
    Props {name = "lanthanum", symbol = "La", charge = 57, color = (0, 0, 0), radius = 195.0},
    Props {name = "cerium", symbol = "Ce", charge = 58, color = (0, 0, 0), radius = 185.0},
    Props {name = "praseodymium", symbol = "Pr", charge = 59, color = (0, 0, 0), radius = 247.0},
    Props {name = "neodymium", symbol = "Nd", charge = 60, color = (0, 0, 0), radius = 206.0},
    Props {name = "promethium", symbol = "Pm", charge = 61, color = (0, 0, 0), radius = 205.0},
    Props {name = "samarium", symbol = "Sm", charge = 62, color = (0, 0, 0), radius = 238.0},
    Props {name = "europium", symbol = "Eu", charge = 63, color = (0, 0, 0), radius = 231.0},
    Props {name = "gadolinium", symbol = "Gd", charge = 64, color = (0, 0, 0), radius = 233.0},
    Props {name = "terbium", symbol = "Tb", charge = 65, color = (0, 0, 0), radius = 225.0},
    Props {name = "dysprosium", symbol = "Dy", charge = 66, color = (0, 0, 0), radius = 228.0},
    Props {name = "holmium", symbol = "Ho", charge = 67, color = (0, 0, 0), radius = 226.0},
    Props {name = "erbium", symbol = "Er", charge = 68, color = (0, 0, 0), radius = 226.0},
    Props {name = "thulium", symbol = "Tm", charge = 69, color = (0, 0, 0), radius = 222.0},
    Props {name = "ytterbium", symbol = "Yb", charge = 70, color = (0, 0, 0), radius = 222.0},
    Props {name = "lutetium", symbol = "Lu", charge = 71, color = (0, 0, 0), radius = 217.0},
    Props {name = "hafnium", symbol = "Hf", charge = 72, color = (0, 0, 0), radius = 208.0},
    Props {name = "tantalum", symbol = "Ta", charge = 73, color = (0, 0, 0), radius = 200.0},
    Props {name = "tungsten", symbol = "W", charge = 74, color = (0, 0, 0), radius = 193.0},
    Props {name = "rhenium", symbol = "Re", charge = 75, color = (0, 0, 0), radius = 188.0},
    Props {name = "osmium", symbol = "Os", charge = 76, color = (0, 0, 0), radius = 185.0},
    Props {name = "iridium", symbol = "Ir", charge = 77, color = (0, 0, 0), radius = 180.0},
    Props {name = "platinum", symbol = "Pt", charge = 78, color = (0, 0, 0), radius = 177.0},
    Props {name = "gold", symbol = "Au", charge = 79, color = (0, 0, 0), radius = 174.0},
    Props {name = "mercury", symbol = "Hg", charge = 80, color = (0, 0, 0), radius = 171.0},
    Props {name = "thallium", symbol = "Tl", charge = 81, color = (0, 0, 0), radius = 156.0},
    Props {name = "lead", symbol = "Pb", charge = 82, color = (0, 0, 0), radius = 154.0},
    Props {name = "bismuth", symbol = "Bi", charge = 83, color = (0, 0, 0), radius = 143.0},
    Props {name = "polonium", symbol = "Po", charge = 84, color = (0, 0, 0), radius = 135.0},
    Props {name = "astatine", symbol = "At", charge = 85, color = (0, 0, 0), radius = 127.0},
    Props {name = "radon", symbol = "Rn", charge = 86, color = (0, 0, 0), radius = 120.0},
    Props {name = "francium", symbol = "Fr", charge = 87, color = (0, 0, 0), radius = 348.0},
    Props {name = "radium", symbol = "Ra", charge = 88, color = (0, 0, 0), radius = 283.0},
    Props {name = "actinium", symbol = "Ac", charge = 89, color = (0, 0, 0), radius = 260.0},
    Props {name = "thorium", symbol = "Th", charge = 90, color = (0, 0, 0), radius = 237.0},
    Props {name = "protactinium", symbol = "Pa", charge = 91, color = (0, 0, 0), radius = 243.0},
    Props {name = "uranium", symbol = "U", charge = 92, color = (0, 0, 0), radius = 240.0},
    Props {name = "neptunium", symbol = "Np", charge = 93, color = (0, 0, 0), radius = 221.0},
    Props {name = "plutonium", symbol = "Pu", charge = 94, color = (0, 0, 0), radius = 243.0},
    Props {name = "americium", symbol = "Am", charge = 95, color = (0, 0, 0), radius = 244.0},
    Props {name = "curium", symbol = "Cm", charge = 96, color = (0, 0, 0), radius = 245.0},
    Props {name = "berkelium", symbol = "Bk", charge = 97, color = (0, 0, 0), radius = 244.0},
    Props {name = "californium", symbol = "Cf", charge = 98, color = (0, 0, 0), radius = 245.0},
    Props {name = "einsteinium", symbol = "Es", charge = 99, color = (0, 0, 0), radius = 245.0},
    Props {name = "fermium", symbol = "Fm", charge = 100, color = (0, 0, 0), radius = 245.0},
    Props {name = "mendelevium", symbol = "Md", charge = 101, color = (0, 0, 0), radius = 245.0},
    Props {name = "nobelium", symbol = "No", charge = 102, color = (0, 0, 0), radius = 245.0},
    Props {name = "lawrencium", symbol = "Lr", charge = 103, color = (0, 0, 0), radius = 245.0},
    Props {name = "rutherfordium", symbol = "Rf", charge = 104, color = (0, 0, 0), radius = 245.0},
    Props {name = "dubnium", symbol = "Db", charge = 105, color = (0, 0, 0), radius = 245.0},
    Props {name = "seaborgium", symbol = "Sg", charge = 106, color = (0, 0, 0), radius = 245.0},
    Props {name = "bohrium", symbol = "Bh", charge = 107, color = (0, 0, 0), radius = 245.0},
    Props {name = "hassium", symbol = "Hs", charge = 108, color = (0, 0, 0), radius = 245.0},
    Props {name = "meitnerium", symbol = "Mt", charge = 109, color = (0, 0, 0), radius = 245.0},
    Props {name = "darmstadtium", symbol = "Ds", charge = 110, color = (0, 0, 0), radius = 245.0},
    Props {name = "roentgenium", symbol = "Rg", charge = 111, color = (0, 0, 0), radius = 245.0},
    Props {name = "copernicium", symbol = "Cn", charge = 112, color = (0, 0, 0), radius = 245.0},
    Props {name = "nihonium", symbol = "Nh", charge = 113, color = (0, 0, 0), radius = 170.0},
    Props {name = "flerovium", symbol = "Fl", charge = 114, color = (0, 0, 0), radius = 245.0},
    Props {name = "moscovium", symbol = "Mc", charge = 115, color = (0, 0, 0), radius = 245.0},
    Props {name = "livermorium", symbol = "Lv", charge = 116, color = (0, 0, 0), radius = 245.0},
    Props {name = "tennessine", symbol = "Ts", charge = 117, color = (0, 0, 0), radius = 245.0},
    Props {name = "oganesson", symbol = "Og", charge = 118, color = (0, 0, 0), radius = 245.0}
  ]
